# === Translation Quality Scoring Test (with your trained model) ===
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 1️⃣ Import Model & Talk Nizer
MODEL_DIR = "./qe_runs/xlmr_qe/best"
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR)
model.eval()

samples = [
    # ===== 정확 번역 (100) =====
    {"ko": "지금 코드를 확인해 주세요.", "en": "Please check the code now."},
    {"ko": "문법 오류를 수정해 주세요.", "en": "Please fix the syntax error."},
    {"ko": "이 코드는 완벽해요.", "en": "This code is perfect."},
    {"ko": "파일을 업로드하지 못했습니다.", "en": "Failed to upload the file."},
    {"ko": "서버가 응답하지 않습니다.", "en": "The server is not responding."},
    {"ko": "다시 시도해 주세요.", "en": "Please try again."},
    {"ko": "비밀번호를 잊어버렸어요.", "en": "I forgot my password."},
    {"ko": "버튼을 클릭해 주세요.", "en": "Please click the button."},
    {"ko": "오늘은 날씨가 좋네요.", "en": "It's a nice day today."},
    {"ko": "저는 커피를 마셨어요.", "en": "I drank coffee."},
    {"ko": "오늘 회의는 몇 시예요?", "en": "What time is the meeting today?"},
    {"ko": "내일 프로젝트가 마감이에요.", "en": "The project deadline is tomorrow."},
    {"ko": "지금 당장 도망쳐!", "en": "Run away right now!"},
    {"ko": "나의 이름은 호준이다.", "en": "My name is Hojun."},
    {"ko": "이메일 주소를 입력해 주세요.", "en": "Please enter your email address."},
    {"ko": "로그인을 시도해 보세요.", "en": "Please try to log in."},
    {"ko": "계정을 생성해 주세요.", "en": "Please create an account."},
    {"ko": "비밀번호를 재설정해 주세요.", "en": "Please reset your password."},
    {"ko": "데이터를 불러오는 중입니다.", "en": "Loading data..."},
    {"ko": "인터넷 연결을 확인해 주세요.", "en": "Please check your internet connection."},
    {"ko": "잠시 후 다시 시도해 주세요.", "en": "Please try again later."},
    {"ko": "결과를 저장했습니다.", "en": "The result has been saved."},
    {"ko": "새로운 파일을 생성했습니다.", "en": "A new file has been created."},
    {"ko": "다운로드가 완료되었습니다.", "en": "The download is complete."},
    {"ko": "이 기능은 사용할 수 없습니다.", "en": "This feature is not available."},
    {"ko": "현재 버전을 업데이트하세요.", "en": "Please update to the latest version."},
    {"ko": "이 페이지를 새로고침하세요.", "en": "Please refresh this page."},
    {"ko": "응답이 없습니다.", "en": "No response received."},
    {"ko": "서버 오류가 발생했습니다.", "en": "A server error has occurred."},
    {"ko": "모든 필드를 입력해 주세요.", "en": "Please fill in all fields."},
    {"ko": "사용자 이름이 이미 존재합니다.", "en": "The username already exists."},
    {"ko": "유효하지 않은 이메일입니다.", "en": "Invalid email address."},
    {"ko": "비밀번호가 일치하지 않습니다.", "en": "Passwords do not match."},
    {"ko": "접속이 거부되었습니다.", "en": "Access denied."},
    {"ko": "로그인이 필요합니다.", "en": "Login is required."},
    {"ko": "업로드가 완료되었습니다.", "en": "Upload completed successfully."},
    {"ko": "다운로드가 취소되었습니다.", "en": "The download was canceled."},
    {"ko": "설정이 저장되었습니다.", "en": "Settings have been saved."},
    {"ko": "알림을 받으시겠습니까?", "en": "Would you like to receive notifications?"},
    {"ko": "확인을 눌러 주세요.", "en": "Please press confirm."},
    {"ko": "취소를 눌러 주세요.", "en": "Please press cancel."},
    {"ko": "지금 업데이트하시겠습니까?", "en": "Would you like to update now?"},
    {"ko": "메시지를 보냈습니다.", "en": "Message sent."},
    {"ko": "사진을 업로드했습니다.", "en": "Photo uploaded."},
    {"ko": "비디오를 재생합니다.", "en": "Playing the video."},
    {"ko": "오디오를 재생합니다.", "en": "Playing the audio."},
    {"ko": "로그아웃되었습니다.", "en": "You have been logged out."},
    {"ko": "로그인이 완료되었습니다.", "en": "Login successful."},
    {"ko": "비밀번호를 변경했습니다.", "en": "Password has been changed."},
    {"ko": "이 파일을 삭제하시겠습니까?", "en": "Do you want to delete this file?"},
    {"ko": "네트워크 속도가 느립니다.", "en": "The network speed is slow."},
    {"ko": "파일이 너무 큽니다.", "en": "The file is too large."},
    {"ko": "권한이 없습니다.", "en": "You do not have permission."},
    {"ko": "시간이 초과되었습니다.", "en": "The operation timed out."},
    {"ko": "비밀번호를 입력해 주세요.", "en": "Please enter your password."},
    {"ko": "계속하려면 동의해 주세요.", "en": "Please agree to continue."},
    {"ko": "결제를 완료해 주세요.", "en": "Please complete the payment."},
    {"ko": "상품이 장바구니에 추가되었습니다.", "en": "The item has been added to your cart."},
    {"ko": "배송이 시작되었습니다.", "en": "Shipping has started."},
    {"ko": "주문이 완료되었습니다.", "en": "Your order is complete."},
    {"ko": "재고가 부족합니다.", "en": "Out of stock."},
    {"ko": "다음 페이지로 이동합니다.", "en": "Moving to the next page."},
    {"ko": "이전 페이지로 돌아갑니다.", "en": "Returning to the previous page."},
    {"ko": "검색 결과가 없습니다.", "en": "No search results found."},
    {"ko": "새로운 알림이 있습니다.", "en": "You have a new notification."},
    {"ko": "새 메시지가 도착했습니다.", "en": "A new message has arrived."},
    {"ko": "오늘은 월요일입니다.", "en": "Today is Monday."},
    {"ko": "지금은 오후 세 시입니다.", "en": "It is 3 p.m. now."},
    {"ko": "회의가 곧 시작됩니다.", "en": "The meeting will start soon."},
    {"ko": "컴퓨터를 다시 시작해 주세요.", "en": "Please restart your computer."},
    {"ko": "시스템이 업데이트되었습니다.", "en": "The system has been updated."},
    {"ko": "프로그램이 설치되었습니다.", "en": "The program has been installed."},
    {"ko": "파일을 복사했습니다.", "en": "File copied."},
    {"ko": "파일을 붙여넣었습니다.", "en": "File pasted."},
    {"ko": "이름을 변경했습니다.", "en": "Name changed."},
    {"ko": "작업이 완료되었습니다.", "en": "The task has been completed."},
    {"ko": "새로운 문서를 작성했습니다.", "en": "A new document has been created."},
    {"ko": "프린터가 연결되었습니다.", "en": "Printer connected."},
    {"ko": "USB 장치를 인식했습니다.", "en": "USB device recognized."},
    {"ko": "저장 공간이 부족합니다.", "en": "Not enough storage space."},
    {"ko": "암호화가 완료되었습니다.", "en": "Encryption completed."},
    {"ko": "복호화가 완료되었습니다.", "en": "Decryption completed."},
    {"ko": "새로운 업데이트가 있습니다.", "en": "A new update is available."},
    {"ko": "시작 버튼을 클릭하세요.", "en": "Click the start button."},
    {"ko": "프로그램을 종료합니다.", "en": "Closing the program."},
    {"ko": "작업을 취소했습니다.", "en": "Task canceled."},
    {"ko": "백업이 완료되었습니다.", "en": "Backup completed."},
    {"ko": "복원이 완료되었습니다.", "en": "Restore completed."},
    {"ko": "데이터를 분석 중입니다.", "en": "Analyzing data."},
    {"ko": "결과를 표시합니다.", "en": "Displaying the results."},
    {"ko": "테스트가 완료되었습니다.", "en": "Test completed."},
    {"ko": "문제가 해결되었습니다.", "en": "The issue has been resolved."},
    {"ko": "도움이 필요하신가요?", "en": "Do you need help?"},
    {"ko": "지원팀에 문의해 주세요.", "en": "Please contact support."},
    {"ko": "새로운 계정을 추가했습니다.", "en": "A new account has been added."},
    {"ko": "사용자 목록을 불러왔습니다.", "en": "Loaded the user list."},
    {"ko": "모든 항목이 선택되었습니다.", "en": "All items have been selected."},

    # ===== 부분 번역 (50) =====
    {"ko": "지금 코드를 확인해 주세요.", "en": "Check your code later."},
    {"ko": "문법 오류를 수정해 주세요.", "en": "Please correct mistakes."},
    {"ko": "파일을 업로드하지 못했습니다.", "en": "The upload failed."},
    {"ko": "서버가 응답하지 않습니다.", "en": "Server not working."},
    {"ko": "다시 시도해 주세요.", "en": "Try once again please."},
    {"ko": "비밀번호를 잊어버렸어요.", "en": "I lost my password."},
    {"ko": "오늘은 날씨가 좋네요.", "en": "Today is beautiful weather."},
    {"ko": "버튼을 클릭해 주세요.", "en": "Click this button please."},
    {"ko": "내일 프로젝트가 마감이에요.", "en": "Tomorrow project ends."},
    {"ko": "지금 당장 도망쳐!", "en": "Escape quickly!"},
    {"ko": "새로운 파일을 생성했습니다.", "en": "Created file new."},
    {"ko": "다운로드가 완료되었습니다.", "en": "Download done."},
    {"ko": "이 기능은 사용할 수 없습니다.", "en": "Feature unavailable."},
    {"ko": "현재 버전을 업데이트하세요.", "en": "Update version now."},
    {"ko": "시간이 초과되었습니다.", "en": "Too slow operation."},
    {"ko": "결제를 완료해 주세요.", "en": "Finish your paying."},
    {"ko": "배송이 시작되었습니다.", "en": "Delivery started."},
    {"ko": "회의가 곧 시작됩니다.", "en": "Meeting will begin soon."},
    {"ko": "시스템이 업데이트되었습니다.", "en": "System updated."},
    {"ko": "파일을 복사했습니다.", "en": "Copied a file."},
    {"ko": "USB 장치를 인식했습니다.", "en": "USB recognized."},
    {"ko": "저장 공간이 부족합니다.", "en": "Storage not enough."},
    {"ko": "암호화가 완료되었습니다.", "en": "Encrypt done."},
    {"ko": "도움이 필요하신가요?", "en": "Need some help?"},
    {"ko": "새로운 계정을 추가했습니다.", "en": "Added new account."},
    {"ko": "로그인을 시도해 보세요.", "en": "Try to sign in."},
    {"ko": "결과를 저장했습니다.", "en": "Results are stored."},
    {"ko": "오늘은 월요일입니다.", "en": "This day is Monday."},
    {"ko": "이전 페이지로 돌아갑니다.", "en": "Go back previous page."},
    {"ko": "주문이 완료되었습니다.", "en": "Order finished."},
    {"ko": "검색 결과가 없습니다.", "en": "No results."},
    {"ko": "모든 필드를 입력해 주세요.", "en": "Fill fields please."},
    {"ko": "유효하지 않은 이메일입니다.", "en": "Invalid mail."},
    {"ko": "접속이 거부되었습니다.", "en": "Connection refused."},
    {"ko": "로그인이 필요합니다.", "en": "Need to login."},
    {"ko": "설정이 저장되었습니다.", "en": "Saved setting."},
    {"ko": "확인을 눌러 주세요.", "en": "Press confirm please."},
    {"ko": "취소를 눌러 주세요.", "en": "Click cancel button."},
    {"ko": "메시지를 보냈습니다.", "en": "Sent the message."},
    {"ko": "새 메시지가 도착했습니다.", "en": "Received new message."},
    {"ko": "새로운 알림이 있습니다.", "en": "Got new notice."},
    {"ko": "지금은 오후 세 시입니다.", "en": "It's 3 pm now."},
    {"ko": "컴퓨터를 다시 시작해 주세요.", "en": "Restart computer please."},
    {"ko": "작업을 취소했습니다.", "en": "Task stopped."},
    {"ko": "프린터가 연결되었습니다.", "en": "Printer is ready."},
    {"ko": "복원이 완료되었습니다.", "en": "Restore done."},
    {"ko": "파일을 붙여넣었습니다.", "en": "Pasted successfully."},
    {"ko": "테스트가 완료되었습니다.", "en": "Testing done."},
    {"ko": "문제가 해결되었습니다.", "en": "Problem fixed."},
    {"ko": "지원팀에 문의해 주세요.", "en": "Ask for support."},

    # ===== 오역 / 무관 문장 (50) =====
    {"ko": "지금 코드를 확인해 주세요.", "en": "I like apples."},
    {"ko": "문법 오류를 수정해 주세요.", "en": "The sky is blue."},
    {"ko": "지금 코드를 삭제해 주세요.", "en": "I'm going to the park."},
    {"ko": "이 코드는 완벽해요.", "en": "Bananas are yellow."},
    {"ko": "나는 밥을 먹었어요.", "en": "He is swimming fast."},
    {"ko": "어제의 나는 달린다", "en": "Fuck you"},
    {"ko": "파일을 업로드하지 못했습니다.", "en": "The dog ran away."},
    {"ko": "서버가 응답하지 않습니다.", "en": "She loves chocolate cake."},
    {"ko": "다시 시도해 주세요.", "en": "The car is red."},
    {"ko": "비밀번호를 잊어버렸어요.", "en": "Today is Sunday."},
    {"ko": "버튼을 클릭해 주세요.", "en": "Fish can fly."},
    {"ko": "오늘은 날씨가 좋네요.", "en": "I want to be a tree."},
    {"ko": "내일 프로젝트가 마감이에요.", "en": "Pandas are cute."},
    {"ko": "지금 당장 도망쳐!", "en": "I love pancakes."},
    {"ko": "이건 전혀 관련이 없어.", "en": "Blue elephants can fly."},
    {"ko": "오늘의 나는 간다.", "en": "Yesterday I stayed home."},
    {"ko": "나의 이름은 호준이다.", "en": "My cat is sleeping."},
    {"ko": "회의가 곧 시작됩니다.", "en": "Water is important for life."},
    {"ko": "주문이 완료되었습니다.", "en": "He is playing soccer."},
    {"ko": "검색 결과가 없습니다.", "en": "The moon is big tonight."},
    {"ko": "로그인을 시도해 보세요.", "en": "I will buy a sandwich."},
    {"ko": "시스템이 업데이트되었습니다.", "en": "I can't swim."},
    {"ko": "파일을 복사했습니다.", "en": "Birds are dancing."},
    {"ko": "암호화가 완료되었습니다.", "en": "Coffee tastes like rain."},
    {"ko": "결제를 완료해 주세요.", "en": "Dogs eat spaghetti."},
    {"ko": "프린터가 연결되었습니다.", "en": "Stars are falling."},
    {"ko": "도움이 필요하신가요?", "en": "Apples talk sometimes."},
    {"ko": "결과를 저장했습니다.", "en": "The world is square."},
    {"ko": "비디오를 재생합니다.", "en": "I am a potato."},
    {"ko": "파일을 붙여넣었습니다.", "en": "Turtles can sing."},
    {"ko": "저장 공간이 부족합니다.", "en": "My shoe is hungry."},
    {"ko": "배송이 시작되었습니다.", "en": "I am invisible now."},
    {"ko": "로그인이 완료되었습니다.", "en": "Cats are made of clouds."},
    {"ko": "새 메시지가 도착했습니다.", "en": "Pineapples rule the world."},
    {"ko": "이전 페이지로 돌아갑니다.", "en": "I slept under the ocean."},
    {"ko": "주문이 완료되었습니다.", "en": "The sun ate my homework."},
    {"ko": "회의가 곧 시작됩니다.", "en": "Bananas can dance."},
    {"ko": "시스템이 업데이트되었습니다.", "en": "Mountains are tired."},
    {"ko": "파일을 복사했습니다.", "en": "My keyboard is sad."},
    {"ko": "암호화가 완료되었습니다.", "en": "The chair sings loudly."},
    {"ko": "결제를 완료해 주세요.", "en": "I am not a toaster."},
    {"ko": "프린터가 연결되었습니다.", "en": "The fish read a book."},
    {"ko": "도움이 필요하신가요?", "en": "Clouds taste like sugar."},
    {"ko": "결과를 저장했습니다.", "en": "I jumped into the sun."},
    {"ko": "비디오를 재생합니다.", "en": "My pen can talk."},
    {"ko": "파일을 붙여넣었습니다.", "en": "The clock is jealous."},
    {"ko": "저장 공간이 부족합니다.", "en": "My fridge is angry."},
    {"ko": "배송이 시작되었습니다.", "en": "The tree is dancing."},
    {"ko": "로그인이 완료되었습니다.", "en": "I forgot my horse."},
    {"ko": "새 메시지가 도착했습니다.", "en": "The pillow is running."},
]


# 3️⃣ Score calculation function
def score_pair(src, mt):
    inputs = tokenizer(
        f"[KO] {src} [EN] {mt}",
        truncation=True,
        padding=True,
        max_length=128,
        return_tensors="pt"
    )
    with torch.no_grad():
        pred = model(**inputs).logits.squeeze().item()
        return float(pred) * 100

# 4️⃣ Evaluation of example sentences
results = []
for s in samples:
    sc = score_pair(s["ko"], s["en"])
    results.append({**s, "score": round(sc, 2)})

for r in results:
    print(r) 
# 5️⃣ View results


df = pd.DataFrame(results)
print(df)

print("\nAverage score:", round(df["score"].mean(), 2))
print("highest score:", round(df["score"].max(), 2))
print("Lowest score:", round(df["score"].min(), 2))
